In [48]:
a = np.loadtxt('out_1.txt')
b = np.loadtxt('gut_1.txt')
print a.shape, b.shape

def predify(a):
    x,y = a.shape
    b = np.zeros((x,y))
    for i in xrange(x):
        for j in xrange(y):
            if a[i,j] > 0.5:
                b[i,j] = 1.0
            else:
                b[i,j] = 0.0
    return b

a = predify(a)
b = predify(b)
c = abs(a - b)
def check(i):
    tot = b[i,:].sum()+a[i,:].sum()
    return 1 - c[i,:].sum()/tot

for i in xrange(2):
    print check(i)
    print a[i,:]
    print b[i,:]
    print

(2, 12) (2, 12)
1.0
[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]

1.0
[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]



In [40]:
y_conv = tf.nn.softmax(tf.matmul(flat,W1) + b1)
a = tf.cast(tf.greater(y_conv,0.5),tf.float32)
b = tf.cast(tf.greater(y_,0.5),tf.float32)
c = tf.abs(a-b)
ab_sum = tf.reduce_sum(a,1)+tf.reduce_sum(b,1)
accuracy = tf.Variable(1.0)-tf.reduce_mean(tf.reduce_sum(c,1))
print y_conv.get_shape()

cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y_conv), reduction_indices=[1]))
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)
lmsq_loss = tf.sqrt(tf.reduce_mean(tf.square(y_conv-y_)))
# train_step = tf.train.GradientDescentOptimizer(0.10).minimize(lmsq_loss)
# correct_prediction = tf.equal(tf.argmax(y_conv,1), tf.argmax(y_,1))

sess = tf.Session()

NameError: name 'tf' is not defined